// Code generated by mkmatrix.go; DO NOT EDIT.

package facetcache

import (
	facetfs "github.com/sirrobot01/facetfs"
)

type fsS struct {
	*cfs
	symlinkExt
}

type fsL struct {
	*cfs
	linkExt
}

type fsSL struct {
	*cfs
	symlinkExt
	linkExt
}

type fsR struct {
	*cfs
	removeExt
}

type fsSR struct {
	*cfs
	symlinkExt
	removeExt
}

type fsLR struct {
	*cfs
	linkExt
	removeExt
}

type fsSLR struct {
	*cfs
	symlinkExt
	linkExt
	removeExt
}

type fsT struct {
	*cfs
	setStatExt
}

type fsST struct {
	*cfs
	symlinkExt
	setStatExt
}

type fsLT struct {
	*cfs
	linkExt
	setStatExt
}

type fsSLT struct {
	*cfs
	symlinkExt
	linkExt
	setStatExt
}

type fsRT struct {
	*cfs
	removeExt
	setStatExt
}

type fsSRT struct {
	*cfs
	symlinkExt
	removeExt
	setStatExt
}

type fsLRT struct {
	*cfs
	linkExt
	removeExt
	setStatExt
}

type fsSLRT struct {
	*cfs
	symlinkExt
	linkExt
	removeExt
	setStatExt
}

type fsV struct {
	*cfs
	statVFSExt
}

type fsSV struct {
	*cfs
	symlinkExt
	statVFSExt
}

type fsLV struct {
	*cfs
	linkExt
	statVFSExt
}

type fsSLV struct {
	*cfs
	symlinkExt
	linkExt
	statVFSExt
}

type fsRV struct {
	*cfs
	removeExt
	statVFSExt
}

type fsSRV struct {
	*cfs
	symlinkExt
	removeExt
	statVFSExt
}

type fsLRV struct {
	*cfs
	linkExt
	removeExt
	statVFSExt
}

type fsSLRV struct {
	*cfs
	symlinkExt
	linkExt
	removeExt
	statVFSExt
}

type fsTV struct {
	*cfs
	setStatExt
	statVFSExt
}

type fsSTV struct {
	*cfs
	symlinkExt
	setStatExt
	statVFSExt
}

type fsLTV struct {
	*cfs
	linkExt
	setStatExt
	statVFSExt
}

type fsSLTV struct {
	*cfs
	symlinkExt
	linkExt
	setStatExt
	statVFSExt
}

type fsRTV struct {
	*cfs
	removeExt
	setStatExt
	statVFSExt
}

type fsSRTV struct {
	*cfs
	symlinkExt
	removeExt
	setStatExt
	statVFSExt
}

type fsLRTV struct {
	*cfs
	linkExt
	removeExt
	setStatExt
	statVFSExt
}

type fsSLRTV struct {
	*cfs
	symlinkExt
	linkExt
	removeExt
	setStatExt
	statVFSExt
}

// wrapFS returns f behind a type that adds exactly the optional facetfs
// interfaces the backend implements.
func wrapFS(f *cfs) facetfs.FileSystem {
	bits := 0
	if f.symlink != nil {
		bits |= 1
	}
	if f.link != nil {
		bits |= 2
	}
	if f.remove != nil {
		bits |= 4
	}
	if f.setstat != nil {
		bits |= 8
	}
	if f.statvfs != nil {
		bits |= 16
	}
	switch bits {
	case 1:
		return fsS{f, symlinkExt{f}}
	case 2:
		return fsL{f, linkExt{f}}
	case 3:
		return fsSL{f, symlinkExt{f}, linkExt{f}}
	case 4:
		return fsR{f, removeExt{f}}
	case 5:
		return fsSR{f, symlinkExt{f}, removeExt{f}}
	case 6:
		return fsLR{f, linkExt{f}, removeExt{f}}
	case 7:
		return fsSLR{f, symlinkExt{f}, linkExt{f}, removeExt{f}}
	case 8:
		return fsT{f, setStatExt{f}}
	case 9:
		return fsST{f, symlinkExt{f}, setStatExt{f}}
	case 10:
		return fsLT{f, linkExt{f}, setStatExt{f}}
	case 11:
		return fsSLT{f, symlinkExt{f}, linkExt{f}, setStatExt{f}}
	case 12:
		return fsRT{f, removeExt{f}, setStatExt{f}}
	case 13:
		return fsSRT{f, symlinkExt{f}, removeExt{f}, setStatExt{f}}
	case 14:
		return fsLRT{f, linkExt{f}, removeExt{f}, setStatExt{f}}
	case 15:
		return fsSLRT{f, symlinkExt{f}, linkExt{f}, removeExt{f}, setStatExt{f}}
	case 16:
		return fsV{f, statVFSExt{f}}
	case 17:
		return fsSV{f, symlinkExt{f}, statVFSExt{f}}
	case 18:
		return fsLV{f, linkExt{f}, statVFSExt{f}}
	case 19:
		return fsSLV{f, symlinkExt{f}, linkExt{f}, statVFSExt{f}}
	case 20:
		return fsRV{f, removeExt{f}, statVFSExt{f}}
	case 21:
		return fsSRV{f, symlinkExt{f}, removeExt{f}, statVFSExt{f}}
	case 22:
		return fsLRV{f, linkExt{f}, removeExt{f}, statVFSExt{f}}
	case 23:
		return fsSLRV{f, symlinkExt{f}, linkExt{f}, removeExt{f}, statVFSExt{f}}
	case 24:
		return fsTV{f, setStatExt{f}, statVFSExt{f}}
	case 25:
		return fsSTV{f, symlinkExt{f}, setStatExt{f}, statVFSExt{f}}
	case 26:
		return fsLTV{f, linkExt{f}, setStatExt{f}, statVFSExt{f}}
	case 27:
		return fsSLTV{f, symlinkExt{f}, linkExt{f}, setStatExt{f}, statVFSExt{f}}
	case 28:
		return fsRTV{f, removeExt{f}, setStatExt{f}, statVFSExt{f}}
	case 29:
		return fsSRTV{f, symlinkExt{f}, removeExt{f}, setStatExt{f}, statVFSExt{f}}
	case 30:
		return fsLRTV{f, linkExt{f}, removeExt{f}, setStatExt{f}, statVFSExt{f}}
	case 31:
		return fsSLRTV{f, symlinkExt{f}, linkExt{f}, removeExt{f}, setStatExt{f}, statVFSExt{f}}
	}
	return f
}

type wfW struct {
	*writeFile
	writerAtExt
}

type wfS struct {
	*writeFile
	syncExt
}

type wfWS struct {
	*writeFile
	writerAtExt
	syncExt
}

// wrapWriteFile returns w behind a type that adds WriteAt and Sync only
// when the backend handle has them.
func wrapWriteFile(w *writeFile) facetfs.File {
	bits := 0
	if w.bwa != nil {
		bits |= 1
	}
	if w.bsync != nil {
		bits |= 2
	}
	switch bits {
	case 1:
		return wfW{w, writerAtExt{w}}
	case 2:
		return wfS{w, syncExt{w}}
	case 3:
		return wfWS{w, writerAtExt{w}, syncExt{w}}
	}
	return w
}
