//go:build ignore

// mkmatrix generates matrix_gen.go: one wrapper type per combination of the
// optional facetfs interfaces, so the cache exposes exactly the capability
// set of its backend. Run via go generate.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"strings"
)

type ext struct {
	letter string // type-name suffix
	field  string // extension holder type
	iface  string // facetfs interface satisfied, for the doc comment
}

func main() {
	fsExts := []ext{
		{"S", "symlinkExt", "facetfs.SymlinkFS"},
		{"L", "linkExt", "facetfs.LinkFS"},
		{"R", "removeExt", "facetfs.RemoveFS"},
		{"T", "setStatExt", "facetfs.SetStatFS"},
		{"V", "statVFSExt", "facetfs.StatVFSFS"},
	}
	fileExts := []ext{
		{"W", "writerAtExt", "io.WriterAt"},
		{"S", "syncExt", "Sync"},
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by mkmatrix.go; DO NOT EDIT.\n\n")
	b.WriteString("package facetcache\n\n")
	b.WriteString("import (\n\tfacetfs \"github.com/sirrobot01/facetfs\"\n)\n\n")

	writeCombos(&b, "fs", fsExts, "*cfs", "f")
	b.WriteString(`// wrapFS returns f behind a type that adds exactly the optional facetfs
// interfaces the backend implements.
func wrapFS(f *cfs) facetfs.FileSystem {
	bits := 0
`)
	for i, e := range fsExts {
		cond := map[string]string{
			"S": "f.symlink != nil", "L": "f.link != nil", "R": "f.remove != nil",
			"T": "f.setstat != nil", "V": "f.statvfs != nil",
		}[e.letter]
		fmt.Fprintf(&b, "\tif %s {\n\t\tbits |= %d\n\t}\n", cond, 1<<i)
	}
	b.WriteString("\tswitch bits {\n")
	for bits := 1; bits < 1<<len(fsExts); bits++ {
		fmt.Fprintf(&b, "\tcase %d:\n\t\treturn %s{f", bits, typeName("fs", fsExts, bits))
		for i, e := range fsExts {
			if bits&(1<<i) != 0 {
				fmt.Fprintf(&b, ", %s{f}", e.field)
			}
		}
		b.WriteString("}\n")
	}
	b.WriteString("\t}\n\treturn f\n}\n\n")

	writeCombos(&b, "wf", fileExts, "*writeFile", "w")
	b.WriteString(`// wrapWriteFile returns w behind a type that adds WriteAt and Sync only
// when the backend handle has them.
func wrapWriteFile(w *writeFile) facetfs.File {
	bits := 0
	if w.bwa != nil {
		bits |= 1
	}
	if w.bsync != nil {
		bits |= 2
	}
	switch bits {
`)
	for bits := 1; bits < 1<<len(fileExts); bits++ {
		fmt.Fprintf(&b, "\tcase %d:\n\t\treturn %s{w", bits, typeName("wf", fileExts, bits))
		for i, e := range fileExts {
			if bits&(1<<i) != 0 {
				fmt.Fprintf(&b, ", %s{w}", e.field)
			}
		}
		b.WriteString("}\n")
	}
	b.WriteString("\t}\n\treturn w\n}\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatalf("format: %v\n%s", err, b.Bytes())
	}
	if err := os.WriteFile("matrix_gen.go", src, 0o644); err != nil {
		log.Fatal(err)
	}
}

func typeName(prefix string, exts []ext, bits int) string {
	var s strings.Builder
	s.WriteString(prefix)
	for i, e := range exts {
		if bits&(1<<i) != 0 {
			s.WriteString(e.letter)
		}
	}
	return s.String()
}

func writeCombos(b *bytes.Buffer, prefix string, exts []ext, base, recv string) {
	_ = recv
	for bits := 1; bits < 1<<len(exts); bits++ {
		var ifaces []string
		fmt.Fprintf(b, "type %s struct {\n\t%s\n", typeName(prefix, exts, bits), base)
		for i, e := range exts {
			if bits&(1<<i) != 0 {
				fmt.Fprintf(b, "\t%s\n", e.field)
				ifaces = append(ifaces, e.iface)
			}
		}
		b.WriteString("}\n\n")
		_ = ifaces
	}
}
